[build]
  command = "# no build command" # no build command
  functions = "netlify/functions"  # Specify the directory where Netlify functions are located
  publish = "."

[[redirects]]
  from = "/api/*"  # Redirect API requests to Netlify functions
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"  # Specify the function path you want to allow CORS for
    [headers.values]
    Access-Control-Allow-Origin = ["http://localhost:4321", "https://example.com", "*"]  # Add a list of origins you want to allow
    Access-Control-Allow-Methods = "GET, POST, PUT"  # Add allowed methods if needed
    Access-Control-Allow-Headers = "Content-Type"  # Add allowed headers if needed
    Cache-Control = "public, max-age=0, must-revalidate"

[functions]
    node_bundler = "esbuild"
    external_node_modules = ["@sparticuz/chromium"]